name: srbench-hff-sr
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - sympy
  - rust
  - pip
  - pip:
      - geppy
      - deap
      - maturin
      - multiprocess
